# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_waysign_wrappers", use_symbols = TRUE, package_name = "waysign")

#' @usage NULL
#' @useDynLib waysign, .registration = TRUE
NULL

create_router <- function() .Call(wrap__create_router)

format_router <- function(router) .Call(wrap__format_router, router)

router_add_path <- function(router, path, id) invisible(.Call(wrap__router_add_path, router, path, id))

router_find_handler <- function(router, path) .Call(wrap__router_find_handler, router, path)


# nolint end
